apiVersion: v1
kind: Service
metadata:
  name: neurovisionlab-api
  labels:
    app.kubernetes.io/name: neurovisionlab
spec:
  selector:
    app.kubernetes.io/name: neurovisionlab
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
